---
apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: uploader
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: uploader
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: uploader:latest
    source:
      git:
        uri: https://github.com/chmouel/go-simple-uploader
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: IMPORT_URL
            value: "github.com/chmouel/go-simple-uploader"
        from:
          kind: ImageStreamTag
          name: golang:latest
          namespace: openshift
      type: Source
    triggers:
      - type: ConfigChange
      - imageChange: {}
        type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: uploader
    name: uploader
  spec:
    replicas: 1
    selector:
      app: uploader
      deploymentconfig: uploader
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: uploader
          deploymentconfig: uploader
      spec:
        containers:
        - image: uploader:latest
          name: uploader
          env:
            - name: UPLOADER_PORT
              value: "9000"
            - name: UPLOADER_DIRECTORY
              value: "/fileuploads"
            - mountPath: /fileuploads
              name: staticfiles
          volumeMounts:
          - mountPath: /fileuploads
            name: staticfiles
        - image: nginxinc/nginx-unprivileged:latest
          name: nginx
          volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: my-nginx-conf
          - mountPath: /fileuploads
            name: staticfiles
        volumes:
        - configMap:
            defaultMode: 420
            name: my-nginx-conf
          name: my-nginx-conf
        - emptyDir: {}
          name: staticfiles
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - uploader
        from:
          kind: ImageStreamTag
          name: uploader:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: uploader
    name: uploader
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: uploader
      deploymentconfig: uploader
kind: List
metadata: {}
